home:
    path: /
    controller: App\Controller\DefaultController::homeAction

about:
    path : /about
    controller: App\Controller\DefaultController::aboutAction

login:
    path : /login
    controller: App\Controller\DefaultController::loginAction

markets:
    path: /markets
    controller: App\Controller\DefaultController::marketsAction

market:
    path: /market/{id}
    controller: App\Controller\DefaultController::marketAction

informations:
    path: /user/informations
    controller: App\Controller\DefaultController::informationsAction

addNewObject:
    path: /add/{name}/{id}
    controller: App\Controller\NewObjectController::newObjectAction

dashboard:
    path : /admin/dashboard
    controller: App\Controller\AdminController::adminAction

adminShowMarkets:
    path : /admin/showMarkets
    controller: App\Controller\AdminController::showMarkets

adminShowUsers:
    path : /admin/showUsers
    controller: App\Controller\AdminController::showUsers

adminShowMessages :
    path: /admin/showMessages
    controller: App\Controller\AdminController::showMessages

updateObject:
    path: /update/{name}/{id}
    controller: App\Controller\UpdateController::updateAction