home:
    path: /
    controller: App\Controller\DefaultController::homeAction

about:
    path : /about
    controller: App\Controller\DefaultController::aboutAction

login:
    path : /login
    controller: App\Controller\DefaultController::loginAction

markets:
    path: /markets
    controller: App\Controller\DefaultController::marketsAction

market:
    path: /market/{id}
    controller: App\Controller\DefaultController::marketAction

informations:
    path: /user/informations
    controller: App\Controller\DefaultController::informationsAction

addNewObject:
    path: /add/{name}/{userId}
    controller: App\Controller\NewObjectController::newObjectAction




